### ISSUE TITLE
Usage of "runtime" and "turns"

### ISSUE THREAD

**Issue by IzGiulio** [informatiCup/informatiCup2023#10]
It is not really clear the purpose of the "runtime" and "turns" in the "Eingabe". Should we create our own simulation with that, or is it just data that you will use later to run the simulation with our solution?

**Comment by bitflipp** [comment]
When evaluating your solution, we will call `docker build` (see "Ausführung") once. Then, for each task, we will
1) call `docker run` (see "Ausführung").
2) read your object definitions from standard output (see "Ausgabe"), but *forcibly remove* the running container after a number of seconds given by property "time". Please take into account any "warm-up" time your solution may require.
3) add your object definitions to the list of given object definitions and run the simulation for (exactly) the number of turns given by property "turns".
