### ISSUE TITLE
Question about time limit

### ISSUE THREAD

**Issue by saecki** [informatiCup/informatiCup2023#13]
`Die Messung der Rechenzeit beginnt mit dem Aufruf von docker run. Nach Ablauf der
maximalen Rechenzeit (siehe Eingabe) wird die Verarbeitung ohne Ergebnis abgebrochen.`

Does this mean that if our solver has already send the output via `stdout`, but is still taking time to shut down some background thread, the solution will be dismissed because it did not adhere to the time limit?

**Comment by bitflipp** [comment]
Any data sent (flushed) to stdout will be considered.


Tobias Schmitz ***@***.***> schrieb am So., 15. Jan. 2023,
14:27:
