### ISSUE TITLE
Log output in Simulator shows wrong resource type

### ISSUE THREAD

**Issue by herrmanno** [informatiCup/informatiCup2023#2]
It seem to me the [simulator](https://profit.phinau.de) generates some odd output:
When a deposit of subtype `1` is connected to a mine, the log states that the deposit _takes_ `[1:x]`, but the connected mine _accepts_ `[0:x]` as resource. Is this behaviour intended and if so, how exactly should one interpret the `[0:x]` in the generated output?

![SCR-20221014-sqa](https://user-images.githubusercontent.com/3965334/195919395-d66f4d99-b194-4ec2-8210-d35fa40b796a.png)

Example Output
```
1 (end): (1, 1) takes [0:3], [0:87] available
1 (end): (1, 5) takes [1:3], [1:117] available
2 (start): (8, 2) accepts [0:3], holds [0:3]
2 (start): (8, 4) accepts [0:3], holds [0:3]
                                        ↑ This digit seems odd
2 (end): (1, 1) takes [0:3], [0:84] available
2 (end): (1, 5) takes [1:3], [1:114] available
```

Profit CLI Export to reproduce
```
[{"width":40,"height":20,"objects":[{"type":"deposit","x":1,"y":1,"subtype":0,"width":6,"height":3},{"type":"deposit","x":1,"y":5,"subtype":1,"width":6,"height":4}],"products":[{"type":"product","subtype":0,"resources":[5,3,0,0,0,0,0,0],"points":10}],"turns":10},[{"type":"factory","x":14,"y":2,"subtype":0},{"type":"mine","x":8,"y":2,"subtype":0},{"type":"mine","x":8,"y":4,"subtype":0},{"type":"combiner","x":12,"y":4,"subtype":0}]]
```

**Comment by bitflipp** [comment]
Fixed, thanks. `[3x0]` should be more obvious.
