### ISSUE TITLE
Typo in cfp-InformatiCup_2023.pdf

### ISSUE THREAD

**Issue by lex-lex** [informatiCup/informatiCup2023#3]
Hi,

es müsste wohl "Endrunde im März 2023" statt "Endrunde im März 2022" in der Datei [` cfp-InformatiCup_2023.pdf`](https://github.com/informatiCup/informatiCup2023/blob/main/cfp-InformatiCup_2023.pdf) heißen. 

Liebe Grüße
Alex

**Comment by AlexPaar** [comment]
Vielen Dank für den Hinweis. Ist behoben. Viele Grüße.
