### ISSUE TITLE
confused about final task

### ISSUE THREAD

**Issue by leslierobbe** [informatiCup/informatiCup2023#5]
Hi! Probably a stupid question but my team is a little confused on what the actual task is. Should we solve all four tasks and get the best outcome possible? Or is the code in "Eingabe" our task to solve? Or should we achieve the best solution possible in any given field which we know nothing about?

**Comment by bitflipp** [comment]
Your solver should work on any given field.

**Comment by leslierobbe** [comment]
And we know nothing about the existing objects in the field?

Should our "Abgabe" just contain a list of objects?

**Comment by bitflipp** [comment]
Please refer to section "Ein- und Ausgabe". Your software will read its tasks (fields) from standard input and write its results to standard output.
